apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: testtutacr.azurecr.io/azvote/azure-vote-front
    newTag: eac2b5e51da5f4529a2f9411cf70688ade3e8a07
  - name: testtutacr.azurecr.io/azvote/azure-vote-back
    newTag: eac2b5e51da5f4529a2f9411cf70688ade3e8a07
resources:
  - manifests.yaml