apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: testtutacr.azurecr.io/azvote/azure-vote-front
    newTag: 28604d3b275d15ce27857f6d7534f7a072c06021
  - name: testtutacr.azurecr.io/azvote/azure-vote-back
    newTag: 28604d3b275d15ce27857f6d7534f7a072c06021
resources:
  - manifests.yaml