apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: testtutacr.azurecr.io/azvote/azure-vote-front
    newTag: 6ae5f23283ad2894e554d7a06481c31dd7bdbae8
  - name: testtutacr.azurecr.io/azvote/azure-vote-back
    newTag: 6ae5f23283ad2894e554d7a06481c31dd7bdbae8
resources:
  - manifests.yaml