apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-arcpg-gh

images:
  - name: gitopsflowacr.azurecr.io/azvote/azure-vote-front
    newTag: d52e7afb896534ade40379d60a5e6db641b1be51
  - name: gitopsflowacr.azurecr.io/azvote/azure-vote-back
    newTag: d52e7afb896534ade40379d60a5e6db641b1be51
resources:
  - manifests.yaml