apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-arcpg-gh

images:
  - name: gitopsflowacr.azurecr.io/azvote/azure-vote-front
    newTag: 697951edefd7317f5be030652e5df6c45705c751
  - name: gitopsflowacr.azurecr.io/azvote/azure-vote-back
    newTag: 697951edefd7317f5be030652e5df6c45705c751
resources:
  - manifests.yaml