apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-arcpg-gh

images:
  - name: gitopsflowacr.azurecr.io/azvote/azure-vote-front
    newTag: a3de6edda392696d8d6bd1a71aee499d551db091
  - name: gitopsflowacr.azurecr.io/azvote/azure-vote-back
    newTag: a3de6edda392696d8d6bd1a71aee499d551db091
resources:
  - manifests.yaml