apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stage

images:
  - name: testtutacr.azurecr.io/azvote/azure-vote-front
    newTag: 6b21cb7bb1c65ddb99389bbfafbd83f054f0db97
  - name: testtutacr.azurecr.io/azvote/azure-vote-back
    newTag: 6b21cb7bb1c65ddb99389bbfafbd83f054f0db97
resources:
  - manifests.yaml