apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stage

images:
  - name: testtutacr.azurecr.io/azvote/azure-vote-front
    newTag: 2b62584dc2d0e2336335cf1eba110f1e3b87cddc
  - name: testtutacr.azurecr.io/azvote/azure-vote-back
    newTag: 2b62584dc2d0e2336335cf1eba110f1e3b87cddc
resources:
  - manifests.yaml